better timezone handling
MycroftAI/skill-date-time pull request #8
Opened 2017-08-11 14:05 UTC by JarbasAI

check if getting timezone for location failed, display would error and we get a speak message saying time is none

missed many common locations for me, added geopy and tzwhere to get timezone from any address

tzwhere is not working, requirements using fork for un-merged PR

2017-08-14 15:20 UTC, Mn0491 commented
@JarbasAI Just wondering, which locations did the time failed for you?

2017-09-08 16:29 UTC, LearnedVector reviewed
@JarbasAI a suggestion. Can you use the geopy library instead. Your pytzwhere library has a few apt dependencies, and we don't want to introduce that for a skill. with geo py you can do this...

```
import geopy from geocoder
g = geocoders.GoogleV3()
g.geocode("los angeles").address
// Los Angeles, CA, USA
```

2017-09-08 16:29 UTC, Mn0491 commented on requirements.txt
> +git+https://github.com/seahawk1986/pytzwhere.git@fix_install
pip install fails right here for me

2017-09-18 17:02 UTC, LearnedVector requested changes
request a change to requirements.txt. remove pytzwhere from it as it fails if apt-get packages are missing.

2017-09-18 17:02 UTC, Mn0491 commented on requirements.txt
> +git+https://github.com/seahawk1986/pytzwhere.git@fix_install
could you remove the pytzwhere from requirements.txt

2017-11-06 22:21 UTC, Mn0491 commented
@JarbasAI can you see above

2018-02-08 20:47 UTC, penrods commented
I've looked in to this a little bit.  I think https://pypi.python.org/pypi/timezonefinder/2.1.2 is a good library and built upon the open work in https://github.com/evansiroky/timezone-boundary-builder, but it comes at a cost of just under 100 MB of storage demands.  This seems a little heavy for a skill.

https://pypi.python.org/pypi/tzwhere is also big, using the same dataset I believe.

So to me the question is whether this should really live inside a skill or if this should be a service provided by a backend.  I lean towards the latter because the info is useful in other skills ("what is the weather like tomorrow afternoon in Stockholm?").

Perhaps this is a case where Mycroft AI shoulders the burden of keeping this sort of information up to date, likely via something like a Google Maps license?

2018-04-30 18:58 UTC, closed without merging